// import './globals.css'
import LeftSideBar from "@/components/LeftSideBar";
import RightSidebar from "@/components/RightSidebar";
import { Box, CssBaseline, Divider, Grid } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CssBaseline />
      <body className={inter.className}>
        <Box sx={{ width: "80%", mx: " auto" }}>
          <Grid container sx={{ height: "100vh" }}>
            <Grid item id="left-sidebar" xs>
              <LeftSideBar />
            </Grid>
            <Divider orientation="vertical" />
            <Grid item id="content" xs={6}>
              {children}
            </Grid>
            <Divider orientation="vertical" />
            <Grid item id="right-sidebar" xs>
              <RightSidebar />
            </Grid>
          </Grid>
        </Box>
      </body>
    </html>
  );
}
